app/models.py
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'


# Загрузка пользователя по id.
@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64), nullable=False)
    category = db.Column(db.String(64))
    ingredients = db.Column(db.String(128))
    steps = db.Column(db.String(128))
    time = db.Column(db.String(12864))
    user_id = db.Column(db.Integer, nullable=False)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, FloatField, RadioField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from app.models import User


class LoginForm(FlaskForm):
    """
    Форма для заполнения данных на вход существующего пользователя
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    """
    Форма для заполнения данных на добавление нового пользователя
    """

    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Пользователь не зарегистрирован! Введите другой email.')


class RecipeForm(FlaskForm):
    """
    Форма для заполнения данных на добавление нового блюда
    """
    title = StringField("Dish", validators=[DataRequired()])
    category = StringField("Category", validators=[DataRequired()])
    ingredients = StringField("Ingredients", validators=[DataRequired()])
    steps = StringField("Steps", validators=[DataRequired()])
    time = StringField("Cook time", validators=[DataRequired()])
    add = SubmitField('Add Recipe')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import config

db = SQLAlchemy()

login = LoginManager()

login.login_view = 'routes.login'


def create_app(config_class=config.config["development"]):
    app = Flask(__name__)
    # Загрузка конфигурации
    app.config.from_object(config_class)

    db.init_app(app)
    login.init_app(app)

    # импорт блупринтов
    from app.routes import bp
    app.register_blueprint(bp)

    with app.app_context():
        db.create_all()

    return app

app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from app import db
from app.forms import LoginForm, RegistrationForm, RecipeForm
from app.models import User, Recipe
from urllib.parse import urlsplit


bp = Blueprint('routes', __name__)


@bp.route('/')
@bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Проверка введенных данных и вход существующего пользователя
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('routes.profile'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is None or not user.check_password(form.password.data):
            flash('Неверный адрес электронной почты или пароль!')
            return redirect(url_for('routes.login'))

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')

        if not next_page or urlsplit(next_page).netloc != '':
            next_page = url_for('routes.profile')

        return redirect(next_page)

    return render_template('login.html', title='Sign In', form=form)


@bp.route('/logout')
def logout():
    logout_user()

    return redirect(url_for('routes.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    """
    Проверка данных н регистрацию и добавление в базу данных нового пользователя
    :return:
    """
    if current_user.is_authenticated:
        return redirect(url_for('routes.profile'))

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash('Поздравляем, теперь вы зарегистрировались в системе!')

        return redirect(url_for('routes.login'))

    return render_template('register.html', title='Register', form=form)


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Отображение страницы профиля, проверка нажатия кнопки удаления и удаление рецепта с базы данных
    :return:
    """

    # проверка нажатия кнопки удаления и удаление рецепта с базы данных
    if request.args.get('delete') == "delete":

        recipe_id = request.args.get('recipe')

        recipe_on_del = Recipe.query.filter_by(id=int(recipe_id)).first()

        db.session.delete(recipe_on_del)
        db.session.commit()

    # считывание всех рецептов с бд и передача на html страницу для отображения
    list_recipes = Recipe.query.filter_by(user_id=current_user.id).all()

    return render_template('profile.html', title='Profile', name=current_user.username,
                           email=current_user.email, list_recipes=list_recipes)


@bp.route('/settings', methods=['GET', 'POST'])
def settings():

    return render_template('settings.html', title="Settings", user=current_user)


@bp.route('/new_recipe', methods=['GET', 'POST'])
def new_recipe():
    """
    Добавление нового рецепта
    :return:
    """

    form = RecipeForm()

    if form.validate_on_submit():
        recipe = Recipe(title=form.title.data, category=form.category.data, ingredients=form.ingredients.data,
                        steps=form.steps.data, time=form.time.data, user_id=current_user.id)

        db.session.add(recipe)
        db.session.commit()

        flash('Блюдо успешно добавлено в список рецептов!')

        return redirect(url_for('routes.profile'))

    return render_template('new_recipe.html', title="new_recipe", form=form)


@bp.route('/recipe', methods=['GET', 'POST'])
def recipe():
    """
    Отображение нового рецепта
    :return:
    """

    recipe_id = request.args.get('recipe')

    current_recipe = Recipe.query.filter_by(id=int(recipe_id)).first()

    return render_template('recipe.html', title='recipe', recipe=current_recipe)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

    <div class="bg"></div>
    <div class="container">

    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul>
                    {% for category, message in messages %}
                        <li>
                            <div class="glass">
                                <h4 align="center">{{ message }}</h4>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <div class="glass">
                <h1 align="center" style="font-size: 400%; text-shadow: 2px 3px 3px teal;">Recipe Book</h1>
        </div>

        {% block content %}{% endblock %}
    </div>
            </div>

</body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="form-signin">
        <h1 class="h3">Sign In</h1>
        <form method="POST" action="{{ url_for('routes.login') }}">
            {{ form.hidden_tag() }}
            <div class="form-floating">
                {{ form.email(class="form-control", placeholder="name@example.com", required=True) }}
                <label for="floatingInput">Email address</label>
                {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-floating">
                {{ form.password(class="form-control", placeholder="Password", required=True) }}
                <label for="floatingPassword">Password</label>
                {% for error in form.password.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="checkbox mb-3">
                <div class="form-check form-switch">
                    {{ form.remember_me(class="form-check-input", value="1", id="rememberMeSwitch") }}
                    <label class="form-check-label" for="rememberMeSwitch"> Remember me</label>
                </div>
            </div>
            {{ form.submit(class="w-100 btn btn-lg btn-primary", style="text-shadow: 2px 3px 3px purple") }}
            <div>
                <a class="w-100 btn btn-lg btn-secondary" style="text-shadow: 2px 3px 3px purple;" href="{{ url_for('routes.register') }}">Registration</a>
            </div>

        </form>
        <p class="copyright">&copy; 2021</p>
    </div>
{% endblock %}

app/templates/new_recipe.html
{% extends "base.html" %}

{% block content %}
    <div class="form-recipe">
        <h1 class="h3">Creating recipe</h1>
        <form method="POST" action="{{ url_for('routes.new_recipe') }}">
            {{ form.hidden_tag() }}
            <div class="form-floating">
                {{ form.title(class="form-control", placeholder="Title", required=True) }}
                <label for="floatingInput">Title</label>
                {% for error in form.title.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="form-floating">
                {{ form.category(class="form-control", placeholder="Category", required=True) }}
                <label for="floatingInput">Category</label>
                {% for error in form.category.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="form-floating">
                {{ form.ingredients(class="form-control", placeholder="Ingredients", required=True) }}
                <label for="floatingInput">Ingredients</label>
                {% for error in form.ingredients.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="form-floating">
                {{ form.steps(class="form-control", placeholder="Steps", required=True) }}
                <label for="floatingInput">Steps</label>
                {% for error in form.steps.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="form-floating">
                {{ form.time(class="form-control", type="time", placeholder="Time", required=True) }}
                <label for="floatingInput">Time</label>
                {% for error in form.steps.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="form-floating">
                {{ form.add(class="w-100 btn btn-lg btn-primary", style="text-shadow: 2px 3px 3px purple") }}
            </div>

            <div>
                <a class="w-100 btn btn-lg btn-secondary" style="text-shadow: 2px 3px 3px purple;" href="{{ url_for('routes.profile') }}">Back</a>
            </div>

        </form>
    </div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}


{% block content %}
    <div class="form-recipe">
        <form>
            <h1 style="margin-bottom: 0px;">Welcome, {{ name }}!</h1>
                <a class="w-100 btn btn-lg btn" style="margin-top: 1px; text-shadow: 3px 4px 3px teal;" href="{{ url_for('routes.settings') }}">Account info</a>
                <a class="w-100 btn btn-lg btn" style="margin-top: 1px; text-shadow: 3px 4px 3px teal;" href="{{ url_for('routes.logout') }}">Log out</a>
        </form>
    </div>

    <p></p>

    <div class="form-recipe">
        <form method="POST" action="{{ url_for('routes.recipe') }}">
            <nav>
                <div>
                    <h3 style="margin-bottom: 0px;">Recipes</h3>
                    <div class="vertical-menu">
                        {% if list_recipes %}
                            <ul>
                                {% for recipe in list_recipes %}
                                    <li>
                                        <a style="font-size: 150%; text-shadow: purple 1px 0 10px;" href="{{ url_for('routes.recipe', recipe=recipe.id) }}">{{ recipe.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <label style="font-size: 150%; color: aqua">Recipes not found...</label>
                        {% endif %}
                    </div>
                </div>
            </nav>

            <div>
                <a class="w-100 btn btn-lg btn-primary" style="margin-top: 1px; text-shadow: 2px 3px 3px purple;" href="{{ url_for('routes.new_recipe') }}">Add Recipe</a>
            </div>
        <form>
    </div>
{% endblock %}

app/templates/recipe.html
{% extends "base.html" %}

{% block content %}
    <div class="form-recipe">
        <form method="POST" action="{{ url_for('routes.recipe') }}">
            <nav>
                <div>
                    <h1>{{ recipe.title }}</h1>
                    <h5>Category</h5>
                    <label class="form-control" style="text-align: center;">{{ recipe.category }}</label>
                    <h5>Ingredients</h5>
                    <textarea class="form-control" style="text-align: center;">{{ recipe.ingredients }}</textarea>
                    <h5>Steps</h5>
                    <textarea class="form-control" style="text-align: center;">{{ recipe.steps }}</textarea>
                    <h5>Time</h5>
                    <label class="form-control" style="text-align: center;">{{ recipe.time }}</label>

                <div style="margin-top: 20px;">
                    <a class="w-100 btn btn-lg btn-primary" style="text-shadow: 1px 1px 2px purple;"
                       href="{{ url_for('routes.profile', delete='delete', recipe=recipe.id)}}">Delete recipe</a>
                    <a class="w-100 btn btn-lg btn-primary" style="text-shadow: 1px 1px 2px purple;" href="{{ url_for('routes.profile') }}">Back</a>
                </div>
                </div>
            </nav>
        </form>
    </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}


{% block content %}
    <div class="form-signin">
        <h1 class="h3">Register</h1>
        <form method="POST" action="{{ url_for('routes.register') }}">
            {{ form.hidden_tag() }}
            <div class="form-floating">
                {{ form.username(class="form-control", placeholder="Username", required=True) }}
                <label for="floatingUsername">Username</label>
                {% for error in form.username.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-floating">
                {{ form.email(class="form-control", placeholder="name@example.com", required=True) }}
                <label for="floatingInput">Email address</label>
                {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-floating">
                {{ form.password(class="form-control", placeholder="Password", required=True) }}
                <label for="floatingPassword">Password</label>
                {% for error in form.password.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-floating">
                {{ form.password2(class="form-control", placeholder="Repeat Password", required=True) }}
                <label for="floatingPassword2">Repeat Password</label>
                {% for error in form.password2.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
                {{ form.submit(class="w-100 btn btn-lg btn-primary", style="text-shadow: 2px 3px 3px purple") }}
            <div>
                <a class="w-100 btn btn-lg btn-secondary" style="text-shadow: 2px 3px 3px purple;" href="{{ url_for('routes.login') }}">Sign in</a>
            </div>
        </form>
        <p class="copyright">&copy; 2021</p>
    </div>
{% endblock %}

app/templates/settings.html
{% extends "base.html" %}

{% block content %}

    <div class="form-recipe">
        <form>
            <h1>Account</h1>
            <h5>Email</h5>
            <label class="form-control" style="text-align: center;">{{ user.email }}></label>
            <h5>Name</h5>
            <label class="form-control" style="text-align: center;">{{ user.username }}</label>
            <a class="w-100 btn btn-lg btn-primary" style="margin-top: 5px; text-shadow: 3px 4px 3px purple" href="{{ url_for('routes.profile') }}">Back</a>
        </form>
    </div>

{% endblock %}